#!/usr/bin/env python

"""
Script used to do the initial installation of development tools and computer setup.
"""

import os

import shutil

from brew import Brew
from subprocess import check_call
from tempfile import NamedTemporaryFile


__BREW_MODULES = [
    "git",
    "go",
    "python3",
]

__DIRECTORY = os.path.dirname(os.path.abspath(__file__))


def install_homebrew_utilities():
    """
    Install utilities through brew install.
    """
    brew = Brew()
    for module in __BREW_MODULES:
        brew.install(module)


def install_xcode_utilities():
    """
    Install XCode tools such as GCC and Make. This will cause a pop-up prompt to walk through for completion.
    """
    check_call([
        "xcode-select",
        "--install",
    ])


def __update_bash_profile(home):
    """
    Update the ..bash_profile with the loading of docker and docker.
    :param home:
    :return:
    """
    bash_profile = ".bash_profile"
    with open(os.path.join(__DIRECTORY, "config", bash_profile)) as bash_profile_added_content_file:
        content = bash_profile_added_content_file.readlines()

    bash_profile_path = os.path.join(home, bash_profile)
    if not os.path.exists(bash_profile_path):
        raise AssertionError("Don't know what I want to do here yet. Bash Profile is missing though.")

    with open(bash_profile_path, "w") as bash_profile_existing_file:
        existing_content = bash_profile_existing_file.readlines()

    with NamedTemporaryFile("w") as named_temp_file:
        for line in content:
            named_temp_file.file.write(line)

        for line in existing_content:
            named_temp_file.file.write(line)

        named_temp_file.file.flush()
        os.rename(named_temp_file.name, os.path.join(home, bash_profile))


def setup_functions_aliases_and_bash_profile():
    """
    Add a .docker and .docker file to be referenced by the .bash_profile, which will also be updated to load up those
    files on start up.
    """
    home = os.path.expanduser("~")

    config_dir = os.path.join(__DIRECTORY, "config")
    for _, dirs, _ in os.walk(config_dir):
        for dir in dirs:
            shutil.copytree(os.path.join(config_dir, dir), os.path.join(home, dir))

    __update_bash_profile(home)


def main():
    """
    Perform the following operations.

    1. Install homebrew.
    2. Install homebrew utilities.
    3. Add docker, docker, and bash profile setup.
    """
    install_homebrew_utilities()
    install_xcode_utilities()
    setup_functions_aliases_and_bash_profile()


if __name__ == "__main__":
    main()
